apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-monitor
  labels:
    app: network-monitor
spec:
  selector:
    matchLabels:
      app: network-monitor
  template:
    metadata:
      labels:
        app: network-monitor
    spec:
      containers:
        - name: network-monitor
          image: network-monitor-image
          ports:
            - containerPort: 8080
